base: &base
  adapter: mysql2
  pool: 10
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  username: root
  password: 
  socket:  /tmp/mysql.sock

development: &development
  <<: *base
  database: surgery_development

test: &test
  <<: *base
  database: surgery_test

production:
  <<: *base
  database: surgery
  
cucumber:
  <<: *test